CREATE DATABASE IF NOT EXISTS SGA_DB;

USE SGA_DB;

CREATE TABLE Usuarios (
    userName VARCHAR(11) NOT NULL,
    names VARCHAR(45) DEFAULT NULL,
    lastNames VARCHAR(45) DEFAULT NULL,
    uPassword VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (userName)
);



INSERT INTO Usuarios VALUES ("JosueMTZ", "JOSUE AARON", "MARTINEZ MARTINEZ", "JO122ZZ");